dist: xenial
language: python
sudo: true
python:
  - '3.5'

before_install:
  - ls -alR $HOME/.cache/pip/http
  - sudo ls -alR $HOME/.cache/pip/http

install:
  - pip3 install -r requirements.txt --upgrade
  - pip3 install -r user_requirements.txt --upgrade
  - pip3 install pytest-cov==2.6.1 codecov python-coveralls
  - pip3 uninstall pytest-capturelog || true
before_script:
  - sh test/spinup_git.sh
script:
  - flake8 --config=tox_tests.ini ./test/
  - flake8 --config=tox_classes.ini ./classes/
  - flake8 ./
  - python3 -W default::Warning -m pytest --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling --cov=chatcommands --cov=helpers test

branches:
  except:
    - deploy
cache:
  directories:
    - $HOME/virtualenv/python3.5.*
    - $HOME/.cache/pip
before_cache:
  - sudo chown -R $USER.$USER $HOME/.cache
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
  - sudo chown -R $USER.$USER /home/travis/.cache
  - rm -f /home/travis/.cache/pip/log/debug.log
  - rm -rf /home/travis/.cache/pip/http
  - ls -alR $HOME/.cache/pip/http
  - sudo ls -alR $HOME/.cache/pip/http
before_deploy:
  - sudo chown -R $USER.$USER $HOME/.cache
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
  - sudo chown -R $USER.$USER /home/travis/.cache
  - rm -f /home/travis/.cache/pip/log/debug.log
  - rm -rf /home/travis/.cache/pip/http
