language: python
sudo: false
python:
  - '2.7'
install:
  - pip install beautifulsoup4 requests websocket-client coverage pytest==2.5.2 phonenumbers flake8 --upgrade
  - pip install regex==2015.06.15
script:
  - flake8 ./
  - python -W default::Warning -m pytest test
branches:
  only:
    - master
    - travis
    - debugging
