language: python
sudo: false
python:
  - '2.7'
install:
  - pip install beautifulsoup4 requests websocket-client coverage pytest phonenumbers flake8 regex==2015.11.22 termcolor --upgrade
script:
  - flake8 ./
  - python -W default::Warning -m pytest test
branches:
  only:
    - master
    - travis
    - debugging
