language: python
sudo: false
python:
  - '3.6'
install:
  - pip3 install -r requirements.txt --upgrade
  - pip3 install -r user_requirements.txt --upgrade
  - pip3 install pytest-cov codecov python-coveralls
script:
  - flake8 --config=tox_tests.ini ./test/
  - flake8 --config=tox_classes.ini ./classes/
  - flake8 ./
  - python3 -W default::Warning -m pytest --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling --cov=chatcommands test
branches:
  only:
    - master
    - travis
    - debugging
cache:
  directories:
    - $HOME/virtualenv/python3.6.*
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
after_success:
  - codecov
  - coveralls
